/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameOver from "./script/GameOver"
import Game from "./script/Game"
import LoadingRT from "./script/LoadingRT"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("script/GameOver.js",GameOver);
		reg("script/Game.js",Game);
		reg("script/LoadingRT.js",LoadingRT);
    }
}
GameConfig.width = 750;
GameConfig.height = 1334;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "vertical";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "gameOver.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
